### ISSUE TITLE
Satellite Symbol Difference between MS2525C and MS2525D

### ISSUE THREAD

**Issue by ottenw** [Esri/joint-military-symbology-xml#185] opened 2015-05-21 16:30 UTC
There is a difference in the positioning of the "dish" on the satellite symbols between MS2525 versions.  Did this occur by design?  Does the difference matter?

![satellite symbol difference](https://cloud.githubusercontent.com/assets/6909159/7753647/723d89de-ffac-11e4-936e-88e5f45e295a.jpg)

**Comment by wmcgrane** [comment] 2015-05-22 12:25
Bill:  Good catch.  I am not aware of any reason for flipping the dish positioning.  It could be a simple error in the drawing of the symbol.  Sans any definitive response either way from the SSMC, I will need to contact the contractor who designed the graphic (when and if he becomes available).

**Comment by kjellmf** [comment] 2015-05-23 14:21
My guess is that this is by design. There are many more satellite symbols in 2525D than in 2525C. I C you basically only have three different satellite symbols. In D you have more than eleven. Here are a few of them:
![image](https://cloud.githubusercontent.com/assets/29217/7784461/ca16982e-0166-11e5-86e7-db5e16d56cab.png)

Having the dish on top makes sense when you compare with the other types of satellites. They all have a similar look and feel. 

Interestingly the 2525C satellite version is still used by the following land units symbols 

[Land Units / Command and Control / Signal / Tactical Satellite](http://explorer.milsymb.net/#/explore/10031000001111000000): 
![image](https://cloud.githubusercontent.com/assets/29217/7784417/2c08d62a-0165-11e5-9691-340a486f7508.png)

[Land Units / Command and Control / Tactical Satellite](http://explorer.milsymb.net/#/explore/10031000001111000000):
![image](https://cloud.githubusercontent.com/assets/29217/7784420/64732538-0165-11e5-809b-392f703acf9e.png)

**Comment by abouffard** [comment] 2015-08-12 17:57
@ottenw , can this issue now be closed?  Perhaps note here what was decided by the SSMC during the "Otten Hour" and then close?

**Comment by ottenw** [comment] 2015-08-13 16:56
@abouffard , there was agreement that the position of the satellite dish on the symbol changed between 2525C and 2525D. The 2525D and latest APP-6 versions match in this instance (that's good!).  A CP is required to change this symbol back to what it used to be.  The question in my mind is, is this worth drafting a CP over, since 2525D is approved, published, and being implemented?

**Comment by joebayles** [comment] 2015-08-13 17:18
:+1:

**Comment by abouffard** [comment] 2015-08-13 20:05
If you decide to draft a CP then we can track that in this repo and then let's close this issue.  If you decide not to write a CP then go ahead and close this issue at that time.

**Comment by wmcgrane** [comment] 2015-08-14 12:37
I agree with Bill Otten that now that 2525D and APP-6 agree on the dish position of the satellite icon, this is a good thing!

I did wonder if the differences were because the dish facing up was to indicate a land-based dish while the dish facing down indicated a space-based dish.  

Anyway, the standards agree now and I think that regardless of which way the dish faces, I think the users understand that the symbol represents a satellite.  As our former Sect'y of State has said "What difference at this point does it make?"    ;-)

-----Original Message-----

**Comment by ottenw** [comment] 2015-08-14 12:45
@abouffard Recommend closure.  This seems to be about a bit of a glitch in the CM process between the publication of 2525C and restructuring/publication of 2525D.  The icons have already changed once, I cannot see changing them again when I believe they are clear and recognizable as is, especially when framed, as space tracks and land units have distinctly different frames, unless one of the groups/customers I support directs me to submit a change (unlikely).

**Closed** 2015-08-14 12:46 UTC
Labels: B - Question, G - Military Team
